name = "SpectroscopyTools"
uuid = "f1436f7a-66ba-4269-a153-8996db8f0853"
version = "0.1.0"
authors = ["Garrek Stemo <8449000+garrekstemo@users.noreply.github.com>"]

[deps]
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
CurveFitModels = "a3c2e87f-4d91-4e5b-9f3a-7c8b6d2e1f0a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
SavitzkyGolay = "c4bf5708-b6a6-4fbe-bcd0-6850ed671584"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
CurveFit = "1.4"
CurveFitModels = "0.1"
Interpolations = "0.16.2"
Peaks = "0.6"
PhysicalConstants = "0.2"
SavitzkyGolay = "0.9"
Unitful = "1.28"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
